
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVDIV MINUS NUMBER PLUS TIMESexpression : ee : e PLUS ee : e MINUS ee : e TIMES ee : e DIV ee : NUMBER'
    
_lr_action_items = {'NUMBER':([0,4,5,6,7,],[3,3,3,3,3,]),'$end':([1,2,3,8,9,10,11,],[0,-1,-6,-2,-3,-4,-5,]),'PLUS':([2,3,8,9,10,11,],[4,-6,-2,-3,-4,-5,]),'MINUS':([2,3,8,9,10,11,],[5,-6,-2,-3,-4,-5,]),'TIMES':([2,3,8,9,10,11,],[6,-6,6,6,-4,-5,]),'DIV':([2,3,8,9,10,11,],[7,-6,7,7,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'e':([0,4,5,6,7,],[2,8,9,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> e','expression',1,'p_expression','gramatica2.py',46),
  ('e -> e PLUS e','e',3,'p_e_suma','gramatica2.py',50),
  ('e -> e MINUS e','e',3,'p_e_resta','gramatica2.py',56),
  ('e -> e TIMES e','e',3,'p_e_mult','gramatica2.py',62),
  ('e -> e DIV e','e',3,'p_e_div','gramatica2.py',68),
  ('e -> NUMBER','e',1,'p_e_valor','gramatica2.py',74),
]
